import { useState } from "react";
import { X, Phone, Clock, Download, Play, FileText, TrendingUp, TrendingDown, Minus } from "lucide-react";
import { Button } from "./ui/button";
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Input } from "./ui/input";
import { toast } from "sonner@2.0.3";

interface AgentCallLogsProps {
  agent: any;
  onClose: () => void;
}

export function AgentCallLogs({ agent, onClose }: AgentCallLogsProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [playingCallId, setPlayingCallId] = useState<number | null>(null);

  const callLogs = [
    {
      id: 1,
      phoneNumber: "+1 (555) 123-4567",
      duration: "4:32",
      timestamp: "2024-01-15 10:30 AM",
      status: "completed",
      sentiment: "positive",
      outcome: "Sale Completed",
      recording: true,
      transcript: "Customer inquired about pricing and made a purchase...",
    },
    {
      id: 2,
      phoneNumber: "+1 (555) 234-5678",
      duration: "2:15",
      timestamp: "2024-01-15 09:15 AM",
      status: "completed",
      sentiment: "neutral",
      outcome: "Information Provided",
      recording: true,
      transcript: "Customer asked general questions about services...",
    },
    {
      id: 3,
      phoneNumber: "+1 (555) 345-6789",
      duration: "0:45",
      timestamp: "2024-01-15 08:45 AM",
      status: "failed",
      sentiment: "negative",
      outcome: "No Answer",
      recording: false,
      transcript: null,
    },
    {
      id: 4,
      phoneNumber: "+1 (555) 456-7890",
      duration: "6:18",
      timestamp: "2024-01-14 04:20 PM",
      status: "completed",
      sentiment: "positive",
      outcome: "Appointment Scheduled",
      recording: true,
      transcript: "Customer scheduled a demo for next week...",
    },
    {
      id: 5,
      phoneNumber: "+1 (555) 567-8901",
      duration: "3:22",
      timestamp: "2024-01-14 02:10 PM",
      status: "completed",
      sentiment: "neutral",
      outcome: "Callback Requested",
      recording: true,
      transcript: "Customer requested to be called back tomorrow...",
    },
  ];

  const filteredLogs = callLogs.filter(
    (log) =>
      log.phoneNumber.includes(searchQuery) ||
      log.outcome.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const getSentimentIcon = (sentiment: string) => {
    switch (sentiment) {
      case "positive":
        return <TrendingUp className="size-4 text-green-600" />;
      case "negative":
        return <TrendingDown className="size-4 text-red-600" />;
      default:
        return <Minus className="size-4 text-slate-600" />;
    }
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case "positive":
        return "bg-green-100 text-green-800";
      case "negative":
        return "bg-red-100 text-red-800";
      default:
        return "bg-slate-100 text-slate-800";
    }
  };

  const handlePlay = (callId: number) => {
    if (playingCallId === callId) {
      setPlayingCallId(null);
      toast.info("Call stopped");
    } else {
      setPlayingCallId(callId);
      toast.success("Call playing");
    }
  };

  const handleDownloadPDF = (log: any) => {
    // Create PDF content
    const pdfContent = `
Call Recording Report
=====================

Phone Number: ${log.phoneNumber}
Date & Time: ${log.timestamp}
Duration: ${log.duration}
Status: ${log.status}
Sentiment: ${log.sentiment}
Outcome: ${log.outcome}

Transcript:
${log.transcript || "No transcript available"}

---
Generated by VoiceAI Platform
    `;

    // Create a blob and download
    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `call-${log.phoneNumber.replace(/\D/g, '')}-${log.timestamp.replace(/[: ]/g, '-')}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    toast.success("Call report downloaded as PDF");
  };

  const handleDownloadTranscript = (log: any) => {
    if (!log.transcript) {
      toast.error("No transcript available");
      return;
    }

    // Create full transcript content
    const transcriptContent = `
Call Transcript
===============

Phone Number: ${log.phoneNumber}
Date & Time: ${log.timestamp}
Duration: ${log.duration}
Agent: ${agent.name}

Transcript:
-----------
${log.transcript}

Additional Details:
- Status: ${log.status}
- Sentiment: ${log.sentiment}
- Outcome: ${log.outcome}

---
Generated by VoiceAI Platform
    `;

    // Create a blob and download as text file
    const blob = new Blob([transcriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `transcript-${log.phoneNumber.replace(/\D/g, '')}-${log.timestamp.replace(/[: ]/g, '-')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    toast.success("Transcript downloaded");
  };

  return (
    <div className="fixed inset-0 bg-black/50 dark:bg-black/80 z-50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-slate-900 rounded-xl shadow-2xl w-full max-w-6xl max-h-[90vh] overflow-y-auto border border-slate-200 dark:border-slate-800">
        {/* Header */}
        <div className="sticky top-0 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 px-6 py-4 z-10">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="text-slate-900 dark:text-white">Call Logs - {agent.name}</h2>
              <p className="text-slate-600 dark:text-slate-400 text-sm">View all call history and recordings</p>
            </div>
            <Button variant="ghost" size="sm" onClick={onClose}>
              <X className="size-4" />
            </Button>
          </div>

          {/* Search */}
          <Input
            placeholder="Search by phone number or outcome..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="dark:bg-slate-800 dark:border-slate-700 dark:text-white"
          />
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="space-y-3">
            {filteredLogs.map((log) => (
              <Card key={log.id} className="border-slate-200 dark:border-slate-800 hover:shadow-md transition-shadow bg-white dark:bg-slate-800">
                <CardContent className="p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <div className="size-10 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                          <Phone className="size-5 text-blue-600 dark:text-blue-400" />
                        </div>
                        <div>
                          <p className="text-slate-900 dark:text-white">{log.phoneNumber}</p>
                          <p className="text-slate-600 dark:text-slate-400 text-sm">{log.timestamp}</p>
                        </div>
                      </div>

                      <div className="flex items-center gap-2 mb-2">
                        <Badge
                          variant={log.status === "completed" ? "default" : "secondary"}
                          className={log.status === "completed" ? "bg-green-500" : "bg-red-500"}
                        >
                          {log.status}
                        </Badge>
                        <Badge variant="outline" className={getSentimentColor(log.sentiment)}>
                          <span className="flex items-center gap-1">
                            {getSentimentIcon(log.sentiment)}
                            {log.sentiment}
                          </span>
                        </Badge>
                        <div className="flex items-center gap-1 text-slate-600 dark:text-slate-400 text-sm">
                          <Clock className="size-4" />
                          {log.duration}
                        </div>
                      </div>

                      <p className="text-slate-900 dark:text-white mb-2">
                        <span className="text-slate-600 dark:text-slate-400">Outcome:</span> {log.outcome}
                      </p>

                      {log.transcript && (
                        <p className="text-slate-600 dark:text-slate-400 text-sm bg-slate-50 dark:bg-slate-700/50 p-2 rounded">
                          {log.transcript}
                        </p>
                      )}
                    </div>

                    <div className="flex flex-col gap-2 ml-4">
                      {log.recording && (
                        <>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handlePlay(log.id)}
                            className="dark:border-slate-700 dark:hover:bg-slate-700"
                          >
                            <Play className="size-4 mr-2" />
                            {playingCallId === log.id ? "Stop" : "Play"}
                          </Button>
                          <Button 
                            variant="outline" 
                            size="sm" 
                            onClick={() => handleDownloadPDF(log)}
                            className="dark:border-slate-700 dark:hover:bg-slate-700"
                          >
                            <Download className="size-4 mr-2" />
                            Download
                          </Button>
                        </>
                      )}
                      {log.transcript && (
                        <Button 
                          variant="outline" 
                          size="sm" 
                          onClick={() => handleDownloadTranscript(log)}
                          className="dark:border-slate-700 dark:hover:bg-slate-700"
                        >
                          <FileText className="size-4 mr-2" />
                          Transcript
                        </Button>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Empty State */}
          {filteredLogs.length === 0 && (
            <div className="text-center py-12">
              <Phone className="size-16 mx-auto mb-4 text-slate-300 dark:text-slate-600" />
              <h3 className="text-slate-900 dark:text-white mb-2">No call logs found</h3>
              <p className="text-slate-600 dark:text-slate-400">
                {searchQuery ? "Try a different search term" : "No calls have been made yet"}
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}